'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Product
    Public Property Id As Integer
    Public Property ProductName As String
    Public Property Quantity As Integer
    Public Property Price As Integer
    Public Property Description As String
    Public Property CatId As Integer
    Public Property Image As String

    Public Overridable Property Category As Category
    Public Overridable Property Orders As ICollection(Of Order) = New HashSet(Of Order)

End Class
